import { useState } from 'react';
import { Link, NavLink, Outlet, useNavigate } from 'react-router-dom';
import { Menu, X, ArrowUpRight, Bell, Heart, Ticket, LogOut } from 'lucide-react';
import { useAuthStore } from '../store/useAuthStore.js';
import { api } from '../api/axios.js';
import { Button, message, Notice } from '../components/ui.js';
export function SiteLayout() {
  const { user, logout } = useAuthStore(); const [open, setOpen] = useState(false); const [email, setEmail] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const navigate = useNavigate();
  const portal = user?.role === 'ADMIN' ? '/admin' : user?.role === 'ORGANIZER' ? '/organizer/dashboard' : '/dashboard';
  return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><Link className="wordmark" to="/" aria-label="Eventra home">eventra<span>✳</span></Link><nav className="desktop-nav" aria-label="Main navigation"><NavLink to="/events">Discover</NavLink><NavLink to="/venues">Venues</NavLink><NavLink to="/resources">Journal</NavLink></nav><div className="header-actions">{user ? <><Link className="icon-button" aria-label="Wishlist" to="/dashboard/wishlist"><Heart size={19} /></Link><Link className="icon-button" aria-label="Notifications" to="/dashboard/notifications"><Bell size={19} /></Link><Link className="btn secondary" to={portal}>{user.name.split(' ')[0]}’s workspace</Link></> : <><Link className="signin" to="/login">Sign in</Link><Link className="btn primary" to="/register?role=ORGANIZER">Create an event <ArrowUpRight size={16} /></Link></>}<button className="icon-button mobile-toggle" aria-label="Open navigation" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header>{open && <nav className="mobile-nav" aria-label="Mobile navigation">{[['Discover','/events'],['Venues','/venues'],['Journal','/resources'],[user ? 'My workspace' : 'Sign in',user ? portal : '/login']].map(([label,to]) => <Link key={to} to={to} onClick={() => setOpen(false)}>{label}</Link>)}{user && <Button variant="secondary" onClick={() => { logout(); setOpen(false); navigate('/'); }}>Sign out</Button>}</nav>}<main id="main"><Outlet /></main><footer><div className="newsletter"><div><span className="eyebrow">A little more life in your inbox</span><h2>Make room for the unexpected.</h2><p>Event updates, thoughtful recommendations, and new experiences.</p></div><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { await api.post('/newsletter/subscribe', { email }); setNotice('You’re on the list.'); setEmail(''); } catch(err) { setNotice(message(err)); } finally { setBusy(false); } }}><label className="sr-only" htmlFor="newsletter">Email address</label><input id="newsletter" type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="Your email address" /><Button busy={busy}>Subscribe</Button>{notice && <Notice>{notice}</Notice>}</form></div><div className="footer-bottom"><Link className="wordmark" to="/">eventra<span>✳</span></Link><span>Experiences worth remembering. Made for India.</span><nav><Link to="/about">About</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></nav><small>© {new Date().getFullYear()} Eventra</small></div></footer></>;
}
const customer = [['Overview','/dashboard'],['Tickets','/dashboard/tickets'],['Orders & refunds','/dashboard/orders'],['Wishlist','/dashboard/wishlist'],['Notifications','/dashboard/notifications'],['My reviews','/dashboard/reviews'],['Profile','/dashboard/profile'],['Settings','/dashboard/settings']];
const organizer = ['dashboard','events','orders','attendees','analytics','coupons','check-in','reviews','payouts','profile','settings'].map(name => [name.replaceAll('-', ' '), `/organizer/${name}`]);
const admin = ['','users','organizers','events','categories','venues','bookings','orders','payments','refunds','coupons','reviews','payouts','notifications','reports','audit-logs','resources','settings'].map(name => [name ? name.replaceAll('-', ' ') : 'Overview', name ? `/admin/${name}` : '/admin']);
export function WorkspaceLayout({ role }: { role: 'customer' | 'organizer' | 'admin' }) { const { logout } = useAuthStore(); const navigate = useNavigate(); const links = role === 'admin' ? admin : role === 'organizer' ? organizer : customer; return <div className="workspace"><aside><span className="eyebrow">{role} workspace</span><nav aria-label={`${role} navigation`}>{links.map(([label,path]) => <NavLink end key={path} to={path}>{label}</NavLink>)}</nav><Button variant="secondary" onClick={() => { logout(); navigate('/login'); }}><LogOut size={16} /> Sign out</Button><Link to="/events" className="back-market"><Ticket size={16} /> Explore events</Link></aside><div className="workspace-content"><Outlet /></div></div>; }
